[global]
checkNewVersion = true
sendAnonymousUsage = false

[log]

# Default: "ERROR"
level = "DEBUG"

[accessLog]

[entryPoints]
[entryPoints.web]
address = ":80"
#[entryPoints.websecure]
#address = ":443"
# Already defined by traefik internal
#[entryPoints.treafik]
#address = ":8080"
[entryPoints.whoami]
address = ":81"
#[entryPoints.swarmpit]
#address = ":82"
[entryPoints.portainer]
address = ":83"

[api]

# Default: false
insecure = true

# Default: true
# dashboard = false

[providers.file]
directory = "/etc/traefik/dynamic"
watch = true

[providers.docker]
# Default: "unix:///var/run/docker.sock"
# TODO socket protection 
#endpoint = "tcp://172.0.0.1:2377"
# Default: "Host(`{{ normalize .Name }}`)"
#defaultRule = "Host(`{{ normalize .Name }}.docker.localhost`)"

# Default: true
exposedByDefault = false

# Default use bridge network
network = "traefik-public"

[providers.swarm]

# Default: "unix:///var/run/docker.sock"
# TODO socket protection 
#endpoint = "tcp://172.0.0.1:2377"

# Default: "Host(`{{ normalize .Name }}`)"
#defaultRule = "Host(`{{ normalize .Name }}.docker.localhost`)"

# Default: true
exposedByDefault = false

# Default use overlay network
network = "proxy-net"
