version: '3'

services:
  proxy:
    image: coelaoss/traefik-v3.0.0-beta5:debian
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - "80:80"
      - "443:443" #
    restart: unless-stopped
    networks:
      - traefik-public
      - proxy-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-public.rule=Host(`localhost`)
      - traefik.http.routers.traefik-public.entrypoints=web,websecure #
      - traefik.http.routers.traefik-public.service=api@internal
      - traefik.http.routers.traefik-public.middlewares=https-redirect #
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https #
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true #
      - traefik.http.routers.traefik-public.tls=true #
      - traefik.http.routers.traefik-public.tls.certresolver=le #

networks:
  traefik-public:
    external: true
  proxy-net:
    external: true
