version: '3'

services:
  app:
    image: swarmpit/swarmpit:latest
    environment:
      - SWARMPIT_DB=http://db:5984
      - SWARMPIT_INFLUXDB=http://influxdb:8086
    networks:
      - proxy-net
      - internal-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 60s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.services.swarmpit-app.loadbalancer.server.port=8080

  db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - proxy-net
      - internal-net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.tcp.services.swarmpit-db.loadbalancer.server.port=5984

  influxdb:
    image: influxdb:1.8
    volumes:
      - influx-data:/var/lib/influxdb
    networks:
      - proxy-net
      - internal-net
    deploy:
      resources:
        limits:
          cpus: '0.60'
          memory: 512M
        reservations:
          cpus: '0.30'
          memory: 128M
      labels:
        - traefik.enable=true
        - traefik.tcp.services.swarmpit-influxdb.loadbalancer.server.port=8086

  agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.44
    networks:
      - proxy-net
      - internal-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      mode: global
      labels:
        - swarmpit.agent=true
        - traefik.enable=true
        - traefik.tcp.services.swarmpit-agent.loadbalancer.server.port=8080
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local

networks:
  proxy-net:
    external: true
  internal-net:
    external: false
