version: '3'

services:

  whoami:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    networks:
      - proxy-net
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.services.sample-whoami.loadbalancer.server.port=80

networks:
  proxy-net:
    external: true
