version: '3'

services:
  proxy:
    image: coelaoss/traefik-v3.0.0-beta5:debian
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.toml:/etc/traefik/traefik.toml
    restart: always
    networks:
      - traefik-public
      - proxy-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-public.entrypoints=web
      - traefik.http.routers.traefik-public.rule=Host(`localhost`)
      - traefik.tcp.routers.proxy.rule=Host(`localhost`)
      - traefik.tcp.routers.proxy.service=api@internal
      #- traefik.tcp.services.router_proxy.loadbalancer.server.port=8080

networks:
  traefik-public:
    external: true
  proxy-net:
    external: true
